### ISSUE TITLE
JointJS doesn't work with newer jQuery Versions (>1.11.1 | > 2.1.1) under Internet Explorer 11

### ISSUE THREAD

**Issue by ColinFrick** [clientIO/joint#117]
When using JointJS with jQuery Version higher than 1.11.1 or 2.1.1 JointJS doesn't work under Internet Explorer 11 (I have not tested any other version).

I receive following error message when constructing the Paper:
```
SCRIPT438: Object doesn't support property or method getElementsByClassName
File: jquery-2.1.3.js, Row: 800, Column: 5
```

It looks like jQuery can't search by className (like find('.rotatable')) on SVG DOM elements.

Chrome and Firefox don't have this problem.

**Comment by DavidDurman** [comment]
Right, I see. We'll look into this. I believe we can just replace all the find() calls on SVG elements with the Vectorizer alternatives (http://jointjs.com/api#v:findOne and http://jointjs.com/api#v:find).

**Comment by ColinFrick** [comment]
Thats great. In the mean time, I have created an issue on the sizzle project: https://github.com/jquery/sizzle/issues/322
This should be fixed in jQuery 3.0.

**Comment by DavidDurman** [comment]
Good stuff!

**Comment by ColinFrick** [comment]
I fixed my problem with the commit ColinFrick/joint@7f3f873b5c205379e7803a6ce1ae33be511c9e2e
Could you give it a glance? Maybe you see a problem with this solution.

**Comment by chill117** [comment]
The major issues with IE have been fixed by PR #159.

There are still probably some issues, but most functionality works now in IE.

**Comment by kumilingus** [comment]
Please use jQuery version < `2.1.1` for now or => `3.0` once released.

**Comment by RupenAnjaria** [comment]
Is this issue have been resolved? Can we still use latest JoinJs with jQuery 2.1.3?

Thank you.

**Comment by kumilingus** [comment]
I suggest to use jQuery `v2.2.1` if possible. If this is not an option a polyfill is needed. e.g.

```javascript
if (SVGElement.prototype.contains === undefined) {
    SVGElement.prototype.contains = function(el) {
        return $.contains(this, el);
    };
}

if (SVGElement.prototype.getElementsByClassName === undefined) {
    SVGElement.prototype.getElementsByClassName = function(className) {
        return this.querySelectorAll('.' + className);
    };
}
```

**Comment by msiadak** [comment]
@kumilingus jQuery 3.0 did not resolve this issue for me, but your polyfill above did.  Thank you!
